### ISSUE TITLE
Dependency discovery for CSS url()

### ISSUE THREAD

**Issue by xy2iii** [zyrolasting/polyglot#29]
I had trouble with including external assets in CSS. From my understanding, polyglot does not do dependency discovery in css files. This can be annoying for a couple of reasons:

- Fonts are not included:

```css
@font-face {
  font-family: 'myfont';
  src: url('myfont.woff2');
}
```
- Directives like background-image don't work:
```css
html {
  background-image: url('coolbackground.png');
}
```

You can work around these by putting them somewhere static, but then the static contents (images, fonts) aren't cache busted when changed, like polyglot does for every asset, and it adds an extra step - I feel it is a bit of a hack.
